### ISSUE TITLE
Adding OmniAuth Gem for Account Creation and Use

### ISSUE THREAD

**Issue by dazzaji** [codeforboston/cambridge_energy_app#24] opened 2015-12-09 01:48 UTC
We can look at this prior Code for Boston "First to Disclose" integration of OmniAuth and with MIT too:

https://github.com/FirstToDisclose/firsttodisclose.net/pull/61#event-272955817 

https://github.com/FirstToDisclose/firsttodisclose.net/pull/47#event-267695158

**Comment by mzagaja** [comment] 2015-12-19 01:16
Duplicate of #3

**Closed as completed by mzagaja** 2015-12-19 01:16 UTC
