### ISSUE TITLE
Cannot create bill while logged in on live site

### ISSUE THREAD

**Issue by mahtai** [codeforboston/cambridge_energy_app#111] opened 2016-04-27 00:22 UTC
"We're sorry, but something went wrong" when logged in on live site. Creating bill works fine as guest.
Note: Bug 15 on Jeremiah's list

**Comment by mahtai** [comment] 2016-05-01 19:37
Hmm. I was able to create a bill when logged in on the live site, but it appears to have created a duplicate as well.

**Comment by mahtai** [comment] 2016-05-01 20:12
Duplication issue not replicated yet. Can still put in bills when logged in.

**Comment by mahtai** [comment] 2016-05-01 20:15
Getting "Something went wrong" now when logged in.

**Comment by mahtai** [comment] 2016-05-01 20:20
More duplication issues, a few "something went wrongs". No observable pattern so far.

**Comment by kvotolato3** [comment] 2016-05-18 00:41
I have entered 3 bills as a logged in user in production and have not gotten the error.

**Comment by mzagaja** [comment] 2016-05-21 00:18
Closing due to lack of reproducible test case.

**Closed as completed by mzagaja** 2016-05-21 00:18 UTC
Labels: bug
