### ISSUE TITLE
Cannot see user profile dropdown menu

### ISSUE THREAD

**Issue by cranti** [codeforboston/cambridge_energy_app#279] opened 2016-08-17 00:41 UTC
The user dropdown menu (with "My Profile" and "Sign Out" options) is available inconsistently.

After logging in, from the main page, I am not able to see the drop down menu by hovering over/clicking on my user name or the arrow to the right of it. 

I _am_ able to see the menu from the team page (https://www.enersaveapp.org/teams/#), but the behavior is odd:
- When I hover over the area and then remove my mouse, it appears/disappears as expected. 
- if I click on the user name/arrow, the menu flashes and quickly disappears. If I click repeatedly, it stops showing up at all

(using Chrome)

**Comment by mzagaja** [comment] 2016-08-17 17:47
Going to note this is likely a duplicate of #248, but confirms it also is an issue in Chrome and adds additional debugging information. Going to close this one and let whoever tackles this post their work in the other issue. Thanks Carolyn!

**Closed as completed by mzagaja** 2016-08-17 17:47 UTC
